northern = Trainline.create(name: 'Northern' , colour: "black")
victoria = Trainline.create(name: 'Victoria')
# Trainline.create(name: 'Piccadily')
# Trainline.create(name: 'District')
# Trainline.create(name: 'Metropolitan')
# Trainline.create(name: 'Central')
# Trainline.create(name: 'Jubilee')

euston = Station.create(name: 'Euston')
moorgate = Station.create(name: 'Moorgate')
kings_cross = Station.create(name: 'Kings Cross')
green_park = Station.create(name: 'Green Park')
waterloo = Station.create(name: 'Waterloo')
bank = Station.create(name: 'Bank')
# Station.create(name: 'Charing Cross')
# Station.create(name: "Earl's Court")
# Station.create(name: 'Embankment')
# Station.create(name: 'Kingsx')
# Station.create(name: 'Baker Street')
# Station.create(name: 'Aldgate')
# Station.create(name: 'Westminster')

 Stop.create(name: 'Moorgate', station: euston, trainline: northern)
 Stop.create(name: 'Hendon', station: euston, trainline: northern)
 Stop.create(name: 'Southgate', station: euston, trainline: northern)
 Stop.create(name: 'Nothfield', station: euston, trainline: northern)
 Stop.create(name: 'Klapham', station: euston, trainline: northern)
 Stop.create(name: 'Finchley', station: euston, trainline: northern)
# Stop.create(Stations_id, Trainline_id)
